In [1]:
import pandas as pd
import scipy.io as sio
import os
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import statsmodels.formula.api as smf
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [2]:
#importing data to python 
leftSacc_mat = sio.loadmat('/Users/SydneyWalker/Desktop/army data ai4vs/compiledData/leftSacc.mat')
leftSacc = leftSacc_mat['leftSacc2']

In [3]:
error_mat = sio.loadmat('/Users/SydneyWalker/Desktop/army data ai4vs/compiledData/allError.mat')
error = error_mat['error2']

In [4]:
#create a new list with a row that contains each of the subject IDs ([i][0])
leftSacc2 = []

for i in range(len(leftSacc)):
    leftSacc2.append(leftSacc[i][0].tolist())

#append the rest of the columns of leftsacc data to each respective subject, exlcuding the trials of empty rows
for i in range(len(leftSacc)):
    for j in range(1,len(leftSacc[i])):
        if len(leftSacc[i][j]) > 0:
            leftSacc2[i].append(leftSacc[i][j])

In [5]:
error2 = []

#create a new list with a row that contains each of the subject IDs ([i][0])
for i in range(len(error)):
    error2.append(error[i][0].tolist())

#append the rest of the columns of error data to each respective subject, exlcuding the trials of empty rows
for i in range(len(error)):
    for j in range(1,len(error[i])):
        if len(error[i][j]) > 0:
            error2[i].append(error[i][j].tolist())

In [6]:
#create new list with a row that contaisn each of the subject IDs ([i][0])
leftSaccade = []
for i in range(len(leftSacc2)):
    leftSaccade.append(leftSacc[i][0].tolist())

#append the rest of the columns of leftsacc data to each respective subject, exlcuding the padded columns of empty lists
for i in range(len(leftSacc2)):
    for j in range(1,len(leftSacc2[i])):
        if len(leftSacc2[i][j][0]) > 0:
            leftSaccade[i].append(leftSacc2[i][j])


In [7]:
#selecting the varibales of interest
for i in range(len(leftSaccade)):
    for j in range(1,len(leftSaccade[i])):
        leftSaccade[i][j] = leftSaccade[i][j][['duration','amp','avgvel']]

In [8]:
leftSaccError = []

#create new list with a row that contaisn each of the subject IDs ([i][0])
for i in range(len(error2)):
    leftSaccError.append(error[i][0].tolist())

#append the rest of the columns of error data to each respective subject, exlcuding the padded columns of empty lists
for i in range(len(error2)):
    for j in range(1,len(error2[i])):
        if len(error2[i][j][0]) > 0:
            leftSaccError[i].append(error2[i][j])

In [9]:
for i in range(len(leftSaccError)):
    if len(leftSaccError[i]) != len(leftSaccade[i]):
        print([i]) 
#checking that the error and leftsaccade data are of the same length

In [10]:
#making this in list format to make each saccade in tuple format so we can append the error
for i in range(len(leftSaccade)):
    for j in range(1,len(leftSaccade[i])):
        leftSaccade[i][j] = leftSaccade[i][j].tolist()

In [11]:
#adding the error to the left saccade data
for i in range(len(leftSaccade)):
    for j in range(1,len(leftSaccade[i])):
        for k in range(len(leftSaccade[i][j][0])):
            leftSaccade[i][j][0][k] = leftSaccade[i][j][0][k] + tuple(leftSaccError[i][j])

In [12]:
# test = []

# for i in range(len(leftSacc)):
#     test.append(leftSacc[i][0].tolist())

# for i in range(len(leftSaccade)):
#     for j in range(1,len(leftSaccade[i])):
#         for row in leftSaccade[i][j][0]:
#             test[i].append(row[0:3])

In [13]:
# len(pd.DataFrame(test))

33

In [14]:
# (leftSaccade[32][172][0][5][3])

[-0.27]

In [15]:
error = []

for i in range(len(leftSaccade)):
    for j in range(1,len(leftSaccade[i])):
        for k in range(len(leftSaccade[i][j][0])):
            error.append(leftSaccade[i][j][0][k][3])

In [16]:
len(leftSaccade[0])

162

In [17]:
errors = []

for i in range(len(leftSacc)):
    errors.append(leftSacc[i][0].tolist())

for i in range(len(leftSaccade)):
    for j in range(1,len(leftSaccade[i])):
        for k in range(len(leftSaccade[i][j][0])):
            errors[i].append(abs(leftSaccade[i][j][0][k][3][0]))


np.mean(errors[32][1:len(errors[32])])



0.18493788819875775

In [18]:
errors2 = []

for i in range(len(leftSacc)):
    errors2.append(leftSacc[i][0].tolist())

for i in range(len(errors2)):
    errors2[i].append(np.mean(errors[i][1:len(errors[i])]))

In [19]:

second_column = [row[1] for row in errors2]



In [20]:
print(np.percentile(second_column,50)) # == 0.20457853244390542

0.20457853244390542


In [21]:
leftSaccade[0][1][0][0]

(array([[4]], dtype=uint8),
 array([[0.67510942]]),
 array([[0.30908282]]),
 [0.33])

In [22]:
for row in leftSaccade:
        print(row[0])

[163]
[256]
[32]
[395]
[424]
[438]
[468]
[482]
[491]
[506]
[532]
[542]
[571]
[578]
[581]
[594]
[616]
[631]
[655]
[671]
[694]
[759]
[778]
[783]
[788]
[798]
[809]
[823]
[824]
[826]
[830]
[831]
[832]


In [23]:
# betterSubj = []

# for row in errors2:
#     if row[1] < 0.20457853244390542:
#         betterSubj.append(row[0])
#         print(row[0])

In [24]:
betterSubj = []

for row in errors2:
    if row[1] < 0.20457853244390542:
        betterSubj.append(row[0][0])
        print(row[0])


[163]
[256]
[32]
[424]
[438]
[571]
[616]
[655]
[671]
[694]
[759]
[798]
[809]
[826]
[831]
[832]


In [25]:
# worseSubj = []

# for row in errors2:
#     if row[1] > 0.20457853244390542:
#         worseSubj.append(row[0])
#         print(row[0])

In [26]:
worseSubj = []

for row in errors2:
    if row[1] > 0.20457853244390542:
        worseSubj.append(row[0][0])
        print(row[0])

[395]
[468]
[482]
[491]
[506]
[532]
[578]
[581]
[594]
[631]
[778]
[783]
[788]
[823]
[824]
[830]


In [27]:
lowPerformer = []

# #all of the trials before len(220)
# for i in range(len(leftSacc)):
#     highPerformer.append(leftSacc[i][0].tolist())

# leftSaccade[3][0] == [395] or 395

# for i in range(len(leftSaccade)):
#         if leftSaccade[i][0] in worseSubj:
#             lowPerformer.append(leftSaccade[i])

# for i in range(len(leftSaccade)):
#     for j in range(1,len(leftSaccade[i])):
#         if leftSaccade[i][0] in worseSubj:
#             lowPerformer[i].append(leftSaccade[i][j])



        # for value in (row[0][0] for row in leftSaccade):
        #     if value in worsePerformer:
        #         lowPerformer[i].append(leftSaccade[i][j])

In [28]:
# for i in range(len(leftSaccade)):
#         if leftSaccade[i][0] in worseSubj:
#             lowPerformer.append(leftSaccade[i])

In [29]:
for i in range(len(leftSaccade)):
        if leftSaccade[i][0][0] in worseSubj:
            lowPerformer.append(leftSaccade[i])

In [30]:
highPerformer = []

for i in range(len(leftSaccade)):
        if leftSaccade[i][0][0] in betterSubj:
            highPerformer.append(leftSaccade[i])

In [31]:
for i in range(len(highPerformer)):
    for j in range(1,len(highPerformer[i])):
        for k in range(len(highPerformer[i][j][0])):
            highPerformer[i][j][0][k] = list(highPerformer[i][j][0][k])



In [32]:
for i in range(len(highPerformer)):
    for j in range(1,len(highPerformer[i])):
        for k in range(len(highPerformer[i][j][0])):
            for l in range(len(highPerformer[i][j][0][k][0:3])):
                    if (highPerformer[i][j][0][k][l]).size == 1:
                        highPerformer[i][j][0][k][l] = float(highPerformer[i][j][0][k][l])

In [33]:
for i in range(len(lowPerformer)):
    for j in range(1,len(lowPerformer[i])):
        for k in range(len(lowPerformer[i][j][0])):
            lowPerformer[i][j][0][k] = list(lowPerformer[i][j][0][k])

In [34]:
for i in range(len(lowPerformer)):
    for j in range(1,len(lowPerformer[i])):
        for k in range(len(lowPerformer[i][j][0])):
            for l in range(len(lowPerformer[i][j][0][k][0:3])):
                    if (lowPerformer[i][j][0][k][l]).size == 1:
                        lowPerformer[i][j][0][k][l] = float(lowPerformer[i][j][0][k][l])

In [40]:
type(lowPerformer[0][0])

list

In [36]:
stop

NameError: name 'stop' is not defined

In [ ]:
# for i in range(len(highPerformer)):
#     for j in range(1,len(highPerformer[i])):
#         for k in range(len(highPerformer[i][j][0])):
#             for l in range(0,2):
#                 if (highPerformer[i][j][0][k][l]).size != 1:
#                     print([i],[j],[0],[k],[l])

In [ ]:
# for i in range(len(highPerformer)):
#     for j in range(1,len(highPerformer[i])):
#         for k in range(len(highPerformer[i][j][0])):
#             for l in range(0,2):
#                 if (highPerformer[i][j][0][k][l]).size != 1:
#                     highPerformer[i][j][0][k].remove(highPerformer[i][j][0][k][l])

In [ ]:
# for i in range(len(highPerformer[15][172][0][5][0:3])):
#     highPerformer[15][172][0][5][i] = float(highPerformer[15][172][0][5][i])

In [ ]:
# data_tuple = [float(highPerformer[15][172][0][5][i]) for i in range(len(highPerformer[15][172][0][5][0:3]))]
# data_tuple

In [ ]:
# highPerformer[15][172][0][5] = list(highPerformer[15][172][0][5])

In [ ]:
# type(highPerformer[15][172][0][5])

In [ ]:
# data_tuple = []

# for i in range(len(highPerformer[15][172][0][5][0:3])):
#     highPerformer[15][172][0][5][i] = float(highPerformer[15][172][0][5][i])

In [ ]:
# data_tuple = []

# for i in range(len(highPerformer[15][172][0][5][0:3])):
#     data_tuple.append(float(highPerformer[15][172][0][5][i]))


In [ ]:
# data_tuple

In [ ]:
# result_list = [float(highPerformer[0][1][0][1][0:3][i][0][0]) for i in range(len(highPerformer[0][1][0][1][0:3]))]

In [ ]:
import csv

with open('lowPerfomer.csv', 'w', newline = '') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(lowPerformer)


with open('highPerformer.csv', 'w', newline = '') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(highPerformer)

In [ ]:
# import scipy.io as sio
# import numpy as np

# my_variable = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# # Create a dictionary with variable names as keys
# data = {'my_variable': my_variable}

# # Save the data to a .mat file
# sio.savemat('data.mat', data)


In [ ]:
# import scipy.io as sio
# import numpy as np

# temp = highPerformer.reshape((1, -1))

# # Create a dictionary with variable names as keys
# data = {'highPerformance': temp}

# # Save the data to a .mat file
# sio.savemat('highPerformance.mat', data)


In [ ]:
for i in range(len(leftSaccade)):
        if leftSaccade[i][0] in worseSubj:
            print(leftSaccade[i][0])

In [ ]:
lowPerformer.append(leftSaccade[0])

In [ ]:
len(lowPerformer)

In [ ]:
if leftSaccade[0][0] == [163] or [218]:
    print(leftSaccade[0][0])

In [ ]:
leftSaccade[3][0] in worseSubj

In [ ]:
list1 = [1, 2, 3, 4, 5]

In [ ]:
list1 = [2, 3, 4, 5]

list1[0] == 2 or 1


In [ ]:
[row[0][0] for row in leftSaccade] 